### ISSUE TITLE
problem with ";"

### ISSUE THREAD

**Issue by chemix** [codenothing/css-compressor#3]
i try this code with "Sane" compression

<pre>.test {
    border-radius: 4px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
}
</pre>

and get 

<pre>
.test {
    border-radius: 4px-webkit-border-top-left-radius:4px-moz-border-radius-topleft:4px;
    -webkit-border-top-right-radius: 4px-moz-border-radius-topleft:4px;
    -webkit-border-bottom-right-radius: 4px-moz-border-radius-topleft:4px;
    -webkit-border-bottom-left-radius: 4px-moz-border-radius-topleft:4px;
    -moz-border-radius-topright: 4px;
    -moz-border-radius-bottomright: 4px;
    -moz-border-radius-bottomleft: 4px
}
</pre>

**Comment by codenothing** [comment]
Been confirmed, patch currently being worked on. This does affect any rule set that uses multiple border-radius definitions.

Quick Fixes: Use 'Safe' mode, or open up custom options, and turn off 'border-radius-combine' option.

**Comment by codenothing** [comment]
Patch committed: https://github.com/codenothing/css-compressor/commit/2b93933e53cca2cd9f47b7a1adc655b87faeb075

**Comment by chemix** [comment]
(thumb-up)

**Comment by codenothing** [comment]
awesome, thanks.
