### ISSUE TITLE
quot mark removed breaks css

### ISSUE THREAD

**Issue by azalea666** [codenothing/css-compressor#5]
a selector such as `a.tagadelic[href="/portfolio/drupal"]` has the double quotes removed from the attribute value making the resulting css invalid.

**Comment by codenothing** [comment]
Is this only an issue with path'd attributes like href? I'm pretty sure simple values are allowed to not have surrounding quotes:

http://www.w3.org/TR/css3-selectors/#attribute-selectors

**Comment by azalea666** [comment]
Apparently string values need to be quoted using either single or double quotes, but identifiers don't have to be. 

This isn't exactly obvious from the spec, but at the link you sent it does say "Attribute values must be CSS identifiers or strings." and that links to http://www.w3.org/TR/CSS21/syndata.html#strings where it does specify that "Strings can either be written with double quotes or with single quotes."

If you look at the examples in the spec, they use quotes too. 

http://reference.sitepoint.com/css/attributeselector confirms this interpretation.

And, if you try to validate the css at http://jigsaw.w3.org/css-validator/ you will get parse errors if there are no quotes. 

Firefox won't recognize the css either - the statement is ignored without quotes. 

i didn't check other browsers, but this seems enough to demonstrate the problem.

**Comment by codenothing** [comment]
Cool, thank you. Will get on this.

**Comment by codenothing** [comment]
https://github.com/codenothing/css-compressor/commit/9168794b3de124f52764e3e81ca43ea7e9ab06d4

**Comment by azalea666** [comment]
cool. thanks for taking care of that so quickly.

**Comment by azalea666** [comment]
are you planning on releasing a new version any time soon? 3.1?

**Comment by codenothing** [comment]
I would assume not for a little while, I have a structure change in the works and need to get that in for the next release.
